[[http://www.gnu.org/licenses/gpl-3.0.txt][file:https://img.shields.io/badge/license-GPL_3-orange.svg]]
[[http://melpa.org/#/point-pos][file:http://melpa.org/packages/point-pos-badge.svg]]
[[http://stable.melpa.org/#/point-pos][file:http://stable.melpa.org/packages/point-pos-badge.svg]]

** About

Emacs package for saving point positions in a ring-like history.

I know about =C-u C-SPC=, registers and bookmarks and I use all of
those, but it's not enough for me, so I wrote this little package.

** Installation

*** Automatic

This package can be installed from [[https://melpa.org/][MELPA]] (with =M-x package-install= or
=M-x list-packages=).

*** Manual

For the manual installation, clone the repo, add the directory to
=load-path= and autoload for =point-pos-save= command:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/path/to/point-pos-dir")
(autoload 'point-pos-save "point-pos" nil t)
#+END_SRC

** Usage

To save current position, use =point-pos-save= command.

To go to a saved position, use =point-pos-goto= / =point-pos-next= /
=point-pos-previous=.

To delete current position, use =point-pos-delete= (with =C-u= delete
all).

** Similar packages

Note that =point-pos= is a very simple package: it just provides several
commands to save / move to / delete positions and that's all!

There is a much more featureful package – [[https://github.com/boyw165/history][history]].  Along with similar
commands, it provides a minor mode with keys and menus, also you can
conveniently choose a history item from minibuffer and do other stuff.

Finally, if you just want to add a history button to the Emacs toolbar,
you may look at [[https://github.com/rolandwalker/back-button][back-button]] package.
